import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Layout from '@/components/layout/Layout'

import PhoneMockup from '../../public/phone-mockup.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Labse Careers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <main className='overflox-x-hidden'>
        <section className='min-h-screen '>
          <div className='flex sm:flex-row items-center justify-center'>
            <div className="grid max-w-screen-xl px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12">
                <div className="mr-auto place-self-center lg:col-span-7">
                  <div className='h-12 sm:h-14 md:h-16 lg:h-[72px] overflow-hidden'>
                    <div className='words'>
                    <h1 className="max-w-2xl mb-4 text-4xl font-extrabold tracking-tight leading-none md:text-5xl xl:text-6xl">
                      <span className='block h-full pl-2 py-2 text-red-500 font-bold'>Rekayasa</span>
                      <span className='block h-full pl-2 py-2 text-green-500 font-bold'>Perangkat</span>
                      <span className='block h-full pl-2 py-2 text-blue-500 font-bold'>Lunak</span>
                    </h1>
                    </div>
                  </div>
                    <h1 className="max-w-2xl mb-4 text-4xl font-bold tracking-tight leading-none md:text-5xl xl:text-6xl text-black dark:text-white">for everyone</h1>
                    <p className="max-w-2xl mb-6 font-sm text-gray-700 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400">Find your future at RPL.</p>
                    <a href="#" className="inline-flex items-center justify-center px-5 py-3 mr-3 text-base font-medium text-center text-black rounded-lg bg-white border-2 border-black hover:bg-black hover:text-white dark:text-white dark:bg-gray-900 dark:border-white dark:hover:bg-white dark:hover:text-black ">
                        Pelatihan
                        <svg className="w-5 h-5 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                    </a>
                    <a href="#" className="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-center text-gray-400 bg-gray-300 rounded focus:outline-none cursor-not-allowed">
                        Oprec Camin
                    </a> 
                </div>
                <div className="lg:mt-0 lg:col-span-5 sm:flex order-first sm:order-last ">
                    <Image src={PhoneMockup} alt="mockup" width={512} height={512}/>
                </div>                
            </div>
          </div>
        </section>
      </main>
      </Layout>
    </>
  )
}
